name: ci

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 

  test: 
    name: Test
    row-on: ubunto-latest

    services: 
      postgres:
        image: postgres:14
        env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: go_finance
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  steps:

  - name: Set up Go 1.x
    uses: actions/setup-go@v2
    with:
      go-version: ^1.15
    id: go

  - name: Check out code into the Go module directory
    uses: actions/checkout@v2

  - name: Install golang-migrate
    run:
      curl -L http://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.Linux-amd64.tar.gz | tar xvz
      sudo mv migrate.linux-amd64 /usr/bin/migrate
      which migrate
  - name: Run migrations
    run: make migrateup

  - name: Run Test
    run: make test